apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    setup.template.name: "filebeat"
    setup.template.pattern: "filebeat-k8s-*"
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - "/log/*"
    fields:
      k8s-app: log-contanier-file
    output.elasticsearch:
      hosts: ["elasticsearch-logging.logging:9200"]
      index: "filebeat-k8s-%{+YYYY.MM.dd}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-contanier-file
  labels:
    k8s-app: log-contanier-file
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: log-contanier-file
  template:
    metadata:
      labels:
        k8s-app: log-contanier-file
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: log-contanier-file
        image: alpine:latest
        command:
        - sh
        - -c
        - 'count=1;while true;do echo log to file $count>>/data/logs/log-contanier-file.log;sleep 1;count=$(($count+1));done'
        volumeMounts:
        - name: app-logs
          mountPath: /data/logs
      - name: filebeat-logging
        image: registry.cn-shanghai.aliyuncs.com/k8s-log/filebeat:6.3.2
        args: [
          "-c", "/etc/filebeat/filebeat.yml",
          "-e",
        ]
        volumeMounts:
        - name: app-logs
          mountPath: /log
        - name: filebeat-config
          mountPath: /etc/filebeat
      volumes:
      - name: app-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: filebeat-config