apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-redis
  namespace: logging
  labels:
    k8s-app: logging-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: logging-redis
  template:
    metadata:
      labels:
        k8s-app: logging-redis
    spec:
      containers:
      - name: logging-redis
        image: redis
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: logging-redis
  namespace: logging
  labels:
    k8s-app: logging-redis
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    k8s-app: logging-redis